### PR TITLE
Use coverxygen for documentation coverage analysis

### PR DESCRIPTION
**Pull request by wiegandm**
This commit modifies the CircleCI configuration to split documentation
generation and documentation coverage analysis.

By using `coverxygen` instead of `doxy-coverage` it also enables support
for submitting the documentation coverage results to `codecov.io`.

### CODE REVIEW

**Comment by mattmundell** [comment]
Do we want @davidak to check this, or can I merge?

**Comment by wiegandm** [comment]
> Do we want @davidak to check this, or can I merge?

Feel free to merge if you approve of this change.

**Comment by wiegandm** [comment]
> Do we want @davidak to check this, or can I merge?

Feel free to merge if you approve of this change.

**Comment by wiegandm** [comment]
> Do we want @davidak to check this, or can I merge?

Feel free to merge if you approve of this change.

**Comment by wiegandm** [comment]
> Do we want @davidak to check this, or can I merge?

Feel free to merge if you approve.

**Comment by wiegandm** [comment]
> Do we want @davidak to check this, or can I merge?

@mattmundell, feel free to go ahead and merge if you approve of the change.

**Pull request merged**
